# 文件路径: .github/workflows/send-emails.yml
# 描述: 修复了总是遗漏最后一个收件人的 bug。

name: Send Bulk Emails (Python Script)

on:
  workflow_dispatch:

jobs:
  prepare-recipients:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare recipient list for matrix
        id: set-matrix
        run: |
          # [已修复] 修正了 jq 命令，不再会错误地删除最后一行
          echo "matrix=$(grep -v '^$' recipients.csv | tail -n +2 | jq -Rsc 'split("\n") | map(split(",")) | map(select(.[0] and .[0] != "")) | map({email: .[0], name: .[1]})')" >> $GITHUB_OUTPUT

  send-mail:
    needs: prepare-recipients
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipient: ${{ fromJson(needs.prepare-recipients.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Send email using Python script
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          # 在这里定义你的附件，用逗号隔开多个文件
          python send_email.py ${{ matrix.recipient.email }} "${{ matrix.recipient.name }}" "screenshot.png, another_file.pdf, document.docx"

