# 文件路径: .github/workflows/send-emails.yml
# 描述: 增加了速率限制控制，确保所有邮件都能成功发送。

name: Send Bulk Emails (Python Script)

on:
  workflow_dispatch:

jobs:
  prepare-recipients:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare recipient list for matrix
        id: set-matrix
        run: |
          # [已更新] 移除了 `tail -n +2`，现在会处理 CSV 中的所有行
          echo "matrix=$(grep -v '^$' recipients.csv | jq -Rsc 'split("\n") | map(split(",")) | map(select(.[0] and .[0] != "")) | map({email: .[0], name: .[1]})')" >> $GITHUB_OUTPUT

  send-mail:
    needs: prepare-recipients
    runs-on: ubuntu-latest
    strategy:
      # [新增] 限制并发数量为1，让邮件一封一封串行发送
      max-parallel: 1
      matrix:
        recipient: ${{ fromJson(needs.prepare-recipients.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Send email using Python script
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          # [新增] 在每次发送前暂停5秒，以避免触发服务器的速率限制
          echo "Waiting for 0.2 seconds before sending next email..."
          sleep 0.2
          
          # 在这里定义你的附件，用逗号隔开多个文件
          python send_email.py ${{ matrix.recipient.email }} "${{ matrix.recipient.name }}" "b5a5723ca5a99989de0439dc64f6e1a303db1b83_2_1380x920.jpeg"

